project/src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    public $Name;

    #[ORM\Column(type: 'string', length: 255)]
    private $Description;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'Products')]
    #[ORM\JoinColumn(nullable: false)]
    private $Category;

    #[ORM\Column(type: 'string', length: 255)]
    private $Image;

    #[ORM\Column(type: 'decimal', precision: 10, scale: '0')]
    private $price;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

}

project/templates/actions.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {# <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous"> #}
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
 </head>

  <body>
    {% block title %}
        <title>Actions</title>
    {% endblock %}

        <header>
  <div class="collapse bg-light" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-black">Онлайн магазин</h4>
          <p class="text-black">☘ Ми піклуємость про якість наших продуктів ☘</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-black">Меню</h4>
          <ul class="list-unstyled">
            <li><a href="/main" class="text-black">Повернутись на головну сторінку</a></li>
            <li><a href="/main/basket" class="text-black">Кошик замовлень</a></li>
            <li><a href="/profile" class="text-black">Приватний кабінет</a></li>
             <li><a href="/main/contacts" class="text-black">Контакти</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-success shadow-sm">
    <div class="container">
        <h4>Навігація</h4>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

    {% block table %}

    {% endblock %}

  </body>
  

</html>

project/templates/basket.html.twig
{% extends 'actions.html.twig' %}


    {% block title %}
        <title>Product Order</title>
    {% endblock %}

    {% block table %}
     <div class="container mt-4">
        <h1> Кошик </h1>
            <div class="row mt-4">
              <br>
    <table class="table table-striped">
      <thead class="table-dark">
      <tr align="center">

        <th scope="col" width="300">Категорія</th>
        <th scope="col" width="450">Назва</th>
        <th scope="col" width="450">Опис</th>
        <th scope="col" width="450">Зображення</th>
        <th scope="col" width="450">Ціна за од</th>
        <th scope="col" width="100">Кількість</th>
         <th scope="col" width="100">Загальна ціна</th>
        <th scope="col" width="200"></th>
        <th scope="col" width="200"></th>
      </thead>
      <tbody>
     
       {% set sum = 0 %}
              {% for product in products %}  
        <tr align="center">
        <td>{{ product.product.category.name|striptags }}</td>
        <th scope="row">{{ product.product.name|striptags }}</th>
        <td>{{ product.product.description|striptags }}</td>
        <td>{{ product.product.image }}</td>
        <td>{{ product.product.price }}</td>
        <td>{{ product.count }}</td> 
         {% set sum = sum + product.product.price %}
   
        <td>{{ product.product.price }}</td>
       <td></td>
     
        <div class="btn btn-lg">
        <td> <a button class="btn btn-outline-success" type="button" href="/main/basket/del/{{ product.id }}">Видалити з кошика</a> </td> 
        </div> 
            
      </tr>
      </tbody>
      {% endfor %} 
    </table>
    </div>
    <div align="right">
    <h4>Всього: {{ sum }} грн</h4>
    </div>
            <br>
             <div align="center">
            <a href="/main/order" class=" btn btn-outline-success">Оформити замовлення</a>
            <a href="/main/basket/drop" class="btn btn-outline-success">Видалити корзину</a>
            <a href="/main/categories" class="btn btn-outline-success">Додати товар</a>
             </div>
            <br>
{% endblock %}

project/templates/category.html.twig
{% extends 'actions.html.twig' %}


    {% block title %}
        <title>Display categories</title>
    {% endblock %}

    {% block table %}
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="text-black">Наші товари</h1>
        <p class="lead text-black">В нашому магазині ви можете замовити товари з представлених категорій <br> або</p>
        <p>
          <a href="/main/products" class="btn btn-outline-success my-2">переглянути всі продукти</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2">

         {% for category in categories %}

        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="100" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Fruits</title><rect width="100%" height="100%" fill="#FFA500"/><text x="40%" y="50%" text font-size="40" fill="black" dy=".3em">{{ category.name }}</text></svg>

            <div class="card-body" align="center">
              <p class="card-text">В цій категорії ви можете обрати для замовлення найкращі {{ category.name }} до вашого столу</p>
                <div class="btn-group">
                  <a type="button" class="btn btn-outline-success" href="/main/{{ category.name }}">Переглянути</a>
                </div>
            </div>
          </div>
        </div>

         {% endfor %}
      </div>
    </div>
  </div>
    {% endblock %}

project/templates/contacts.html.twig
{% extends 'actions.html.twig' %}

{% block table %}
<!-- Contact Us Section -->
    <section class="Material-contact-section section-padding section-dark">
      <div class="container">
          <div class="row">
              <!-- Section Titile -->
              <div class="col-md-12 wow animated fadeInLeft" data-wow-delay=".2s">
                  <br>
                  <h1 class="section-title">Наші контакти</h1>
              </div>
          </div>
          <div class="row">
              <!-- Section Titile -->
              <div class="col-md-6 mt-3 contact-widget-section2 wow animated fadeInLeft" data-wow-delay=".2s">

                <div class="find-widget">
                <br>
                 Компанія: FreshProducts
                </div>
                <div class="find-widget">
                 <br>
                 Адреса: Україна, м. Харків
                </div>
                <div class="find-widget">
                 <br>
                  Телефон:  + 38-050-000-00-00
                </div>
                <div class="find-widget">
                 <br>
                  Сайт:  <a href="/main">www.freshproducts.com</a>
                </div>
                <div class="find-widget">
                 <br>
                   Графік роботи: Пн-Пт: 09:00 - 18.00
                </div>
              </div>
              <!-- contact form -->
              <div class="col-md-6 wow animated fadeInRight" data-wow-delay=".2s">
              <h4> Зворотній зв'язок</h4>
                  <form class="shake" role="form" method="post" id="contactForm" name="contact-form" data-toggle="validator">
                      <!-- Name -->
                      <div class="form-group label-floating">
                        <label class="control-label" for="name">Ім'я</label>
                        <input class="form-control" id="name" type="text" name="name" required data-error="Please enter your name">
                        <div class="help-block with-errors"></div>
                      </div>
                      <!-- email -->
                      <div class="form-group label-floating">
                        <label class="control-label" for="email">Email</label>
                        <input class="form-control" id="email" type="email" name="email" required data-error="Please enter your Email">
                        <div class="help-block with-errors"></div>
                      </div>
                      <!-- Subject -->
                      <div class="form-group label-floating">
                        <label class="control-label">Тема</label>
                        <input class="form-control" id="msg_subject" type="text" name="subject" required data-error="Please enter your message subject">
                        <div class="help-block with-errors"></div>
                      </div>
                      <!-- Message -->
                      <div class="form-group label-floating">
                          <label for="message" class="control-label">Повідомлення</label>
                          <textarea class="form-control" rows="3" id="message" name="message" required data-error="Напишіть нам"></textarea>
                          <div class="help-block with-errors"></div>
                      </div>
                      <!-- Form Submit -->
                      <div class="form-submit mt-5">
                          <button class="btn btn-common btn-outline-success my-2" type="submit" id="form-submit"> Надіслати повідомлення</button>
                          <div id="msgSubmit" class="h3 text-center hidden"></div>
                          <div class="clearfix"></div>
                      </div>
                  </form>
              </div>
          </div>
      </div>
    </section>
    {% endblock %}

project/templates/fruits.html.twig
{% extends 'category.html.twig' %}

{% block title %}
    <title>Display fruits</title>
{% endblock %}

{% block table %}
  <br>
    <h3 align="center" style="color:Green"> Фрукти </h3>
  <br>

    <table class="table table-striped">
      <thead class="table-dark">
      <tr align="center">
        <th scope="col" width="300">Категорія</th>
        <th scope="col" width="450">Назва</th>
        <th scope="col" width="450">Опис</th>
        <th scope="col" width="450">Зображення</th>
        <th scope="col" width="450">Ціна</th>
        <th scope="col" width="200"></th>
        <th scope="col" width="200"></th>
      </thead>
     {% for product in products %}
            {% if product.category.name == 'фрукти' %}
      <tbody>
      <tr align="center">
        <th scope="row">{{ product.category.name }}</th>
        <td>{{ product.name }}</td>
        <td>{{ product.description }}</td>
        <td>{{ product.image }}</td>
        <td>{{ product.price }}</td>
        <td> <a button class="btn btn-outline-success" type="button" href="/main/{{ product.id }}">Переглянути</a> </td> 
        <td> <a button class="btn btn-outline-success" type="button" href="/main/product_order/{{ product.id }}">Купити</a> </td> 
      </tr>
      </tbody>
         {% endif %}
      {% endfor %}
    </table>
{% endblock %}

project/templates/index.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %} 
    </head>
    <header class="bg-success bg-gradient"> 
        {% block hello %}
            <h1 align="center" class="text-black">Ласкаво просимо до онлайн магазину!</h1>
            <h5 align="center" class="text-black">☘ Ми піклуємость про якість наших продуктів ☘<br><br></h5>
        {% endblock %}
    </header>
    <body background="https://images7.alphacoders.com/498/thumb-1920-498617.jpg">
    <nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
        <ul class="mb-0 h4">
            <li class="mb-4"><a class="text-success" href="/main/categories">Продукція</a></li>
            <li class="mb-4"><a class="text-success" href="/main/basket">Кошик замовлень</a></li>
            <li class="mb-4"><a class="text-success" href="/profile">Приватний кабінет</a></li>
            <li class="mb-4"><a class="text-success" href="/main/contacts">Контакти</a></li>
            
            <li><form class="d-flex" role="search" method="get" action="{{ path('search') }}">
                <input class="form-control me-2" type="text"  name="name" placeholder="Знайти продукт..." aria-label="Search"></input> 
                <button class="btn btn-outline-success" type="submit">Пошук</button></li>
             <div class="d-grid gap-2 d-md-block">
                <a type="button" class="btn btn-outline-success my-4" href="/registration">Реєстрація</a>
                <a type="button" class="btn btn-outline-success" href="/login">Авторизація</a>
                <a type="button" class="btn btn-outline-success" href="/admin">Адмін</a>
     </div>
                </form>
        </ul>
    </div>
   {% block table %}
    {% endblock %}
    </nav>
    </body>
</html>

project/templates/order.html.twig
{% extends 'actions.html.twig' %}

{% block title %}
    <title>Order</title>
{% endblock %}

{% block table %}
  <html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <link rel="stylesheet" href="css/style.css">

    <link rel="icon" href="Favicon.png">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
</head>

<main class="login-form pt-4">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-3">
                <div class="card">
                    <div class="card-header"><h3>Контактні дані</h3></div>
                    <div class="card-body">
                        {{ form_start(form) }}
                            <div class="form-group row">
                                <div class="col-md-4">
                                    {{ form_row(form.adress) }}
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-4">
                                     {{ form_row(form.phone) }}
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-4">
                                    {{ form_row(form.user_name) }}
                                </div>
                            </div>

                            <div class="col-md-3 offset-md-2">
                                <button type="submit" class="btn btn-success">Зберегти</button>
                                </div>
                           </div>
                          {{ form_end(form) }}  
                   
                </div>
            </div>
        </div>
    </div>
    </div>
    </main>
{% endblock %}

project/templates/product_card.html.twig
{% extends 'actions.html.twig' %}


{% block title %}
    <title>Display product</title>
{% endblock %}

{% block table %}
<div class="height d-flex  p-5 pt-6 justify-content-center align-items-center">
    
    <div class="card p-5 pt-6 border border-3 border-warning w-25">
        
        <div class="d-flex justify-content-between align-items-center">
            <div class="mt-2">
                <h6 class="text-uppercase">{{ product.category.name }}</h6>
                <div class="mt-5">
                    <h2 class="text-uppercase mb-0">{{ product.name }}</h2>
                    <h3 class="main-heading mt-0"> Ціна: {{ product.price }} грн</h3>
                    <div class="d-flex flex-row user-ratings">
                        <div class="ratings">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        </div>
                    </div>
                </div>
            </div>
            <div class="image border border-3">
                <img src="{{ product.image }}" alt="фото товару" width="150">
            </div>
        </div>
        
        <div class="d-flex justify-content-between align-items-center mt-2 mb-2">
            <span>Опис продукту:</span>
        </div>
        
        
        <p>{{ product.description }}</p>
        
        <a button class="btn btn-success" type="button" href="/main/product_order/{{ product.id }}">Додати в кошик</a> 
        <a button class="btn btn-outline-success" type="button" href="/main/products">Повернутися до товарів</a> 
    </div>
    
</div>

{% endblock %}

project/templates/product_order.html.twig
{% extends 'actions.html.twig' %}


    {% block title %}
        <title>Product Order</title>
    {% endblock %}

    {% block table %}
     <div class="container mt-4">
        <h1> Замовлення продукту </h1>
            <div class="row mt-4">
              <br>
    <table class="table table-striped">
      <thead class="table-dark">
      <tr align="center">
        <th scope="col" width="300">Категорія</th>
        <th scope="col" width="450">Назва</th>
        <th scope="col" width="450">Опис</th>
        <th scope="col" width="450">Зображення</th>
        <th scope="col" width="450">Ціна</th>
        <th scope="col" width="100"></th>
        <th scope="col" width="200"></th>
      </thead>
      <tbody>
      <tr align="center">   
        <th scope="row">{{ product.category.name }}</th>
        <td>{{ product.name }}</td>
        <td>{{ product.description }}</td>
        <td>{{ product.image }}</td>
        <td>{{ product.price }}</td>
        <div class="btn-group btn-group-lg" role="group">
        <td> <a button class="btn btn-outline-success" type="button" href="/main/products">Повернутись до списку продуктів</a> </td> 
        <td> <a button class="btn btn-success" type="button" href="{{ path('basket_add', {'id': id}) }}">Покласти товар у кошик</a> </td>

{% endblock %}

project/templates/products_list.html.twig
{% extends 'actions.html.twig' %}

{% block title %}
    <title>Display products</title>
{% endblock %}

{% block table %}
  <br>
    <h3 align="center" style="color:Green"> Продукти </h3>
  <br>
    <table class="table table-striped">
      <thead class="table-dark">
      <tr align="center">
        <th scope="col" width="300">Категорія</th>
        <th scope="col" width="450">Назва</th>
        <th scope="col" width="450">Опис</th>
        <th scope="col" width="450">Зображення</th>
        <th scope="col" width="450">Ціна</th>
        <th scope="col" width="200"></th>
        <th scope="col" width="200"></th>
      </thead>
      {% for product in products %}
      <tbody>
      <tr align="center">
        <th scope="row">{{ product.category.name }}</th>
        <td>{{ product.name }}</td>
        <td>{{ product.description }}</td>
        <td>{{ product.image }}</td>
        <td>{{ product.price }}</td>
        <td> <a button class="btn btn-outline-success" type="button" href="/main/{{ product.id }}">Переглянути </a> </td> 
        <td> <a button class="btn btn-outline-success" type="button" href="/main/product_order/{{ product.id }}">Купити </a> </td> 
      </tr>
      </tbody>
      {% endfor %}
    </table>
{% endblock %}

project/templates/registration.html.twig
{% extends 'actions.html.twig' %}


    {% block title %}
        <title>Registration</title>
    {% endblock %}

    {% block table %}
    <html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <link rel="stylesheet" href="css/style.css">

    <link rel="icon" href="Favicon.png">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
</head>

<main class="login-form pt-4">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header"><h3>Форма авторизації</h3></div>
                    <div class="card-body">
                        {{ form_start(registrationForm) }}
                            <div class="form-group row">
                                <label for="name" class="col-md-5 col-form-label text-md-right">Ім'я</label>
                                <div class="col-md-6">
                                    {{ form_row(registrationForm.name) }}
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="phone" class="col-md-5 col-form-label text-md-right">Телефон</label>
                                <div class="col-md-6">
                                    {{ form_row(registrationForm.phone) }}
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="adress" class="col-md-5 col-form-label text-md-right">Адреса</label>
                                <div class="col-md-6">
                                    {{ form_row(registrationForm.adress) }}
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email" class="col-md-5 col-form-label text-md-right">Email</label>
                                <div class="col-md-6">
                                    {{ form_row(registrationForm.email) }}
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password" class="col-md-5 col-form-label text-md-right">Пароль</label>
                                <div class="col-md-6">
                                    {{ form_row(registrationForm.plainPassword) }}
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-6 offset-md-4">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="remember"> Запам'ятати мене
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-success">
                                    Реєстрація
                                </button>
                                <a href="#" class="btn btn-link">
                                    Забули свій пароль?
                                </a>
                                
                            </div>
                    </div>
                   {{ form_end(registrationForm) }}
                </div>
            </div>
        </div>
    </div>
    </div>
    </main>
    {% endblock %}

project/templates/search.html.twig
{% extends 'actions.html.twig' %}


    {% block title %}
        <title>Search of Products</title>
    {% endblock %}

    {% block table %}
    <br>
    <h3 align="center" style="color:Green"> Продукти </h3>
  <br>
    <table class="table table-striped">
      <thead class="table-dark">
      <tr align="center">
        <th scope="col" width="450">Категорія</th>
        <th scope="col" width="450">Назва</th>
        <th scope="col" width="450">Опис</th>
        <th scope="col" width="450">Зображення</th>
        <th scope="col" width="450">Ціна</th>
        <th scope="col" width="150"></th>
        <th scope="col" width="150"></th>
      </thead>
      {% for product in products %}
      <tbody>
      <tr align="center">
        <th scope="row">{{ product.category.name }}</th>
        <td>{{ product.name }}</td>
        <td>{{ product.description }}</td>
        <td>{{ product.image }}</td>
        <td>{{ product.price }}</td>
        <td> <a button class="btn btn-outline-success" type="button" href="#">Переглянути продукт</a> </td> 
        <td> <a button class="btn btn-outline-success" type="button" href="#">Покласти в кошик</a> </td> 
      </tr>
      </tbody>
      {% endfor %}
    </table>


    {% endblock %}

project/templates/vegetables.html.twig
{% extends 'category.html.twig' %}

{% block title %}
    <title>Display vegetables</title>
{% endblock %}

{% block table %}
  <br>
    <h3 align="center" style="color:Green"> Овочі </h3>
  <br>

    <table class="table table-striped">
      <thead class="table-dark">
      <tr align="center">
        <th scope="col" width="300">Категорія</th>
        <th scope="col" width="450">Назва</th>
        <th scope="col" width="450">Опис</th>
        <th scope="col" width="450">Зображення</th>
        <th scope="col" width="450">Ціна</th>
        <th scope="col" width="200"></th>
        <th scope="col" width="200"></th>
      </thead>
     {% for product in products %}
            {% if product.category.name == 'овочі' %}
      <tbody>
      <tr align="center">
        <th scope="row">{{ product.category.name }}</th>
        <td>{{ product.name }}</td>
        <td>{{ product.description }}</td>
        <td>{{ product.image }}</td>
        <td>{{ product.price }}</td>
        <td> <a button class="btn btn-outline-success" type="button" href="/main/{{ product.id }}">Переглянути</a> </td> 
        <td> <a button class="btn btn-outline-success" type="button" href="/main/product_order/{{ product.id }}">Купити</a> </td> 
      </tr>
      </tbody>
         {% endif %}
      {% endfor %}
    </table>
{% endblock %}